# Generated by Django 4.2.17 on 2024-12-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
