# Generated by Django 4.2.17 on 2024-12-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindness', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='title',
            new_name='item_name',
        ),
    ]
