# Generated by Django 4.2.17 on 2024-12-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindness', '0004_rename_title_donation_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('CLAIMED', 'Claimed'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLAIMED', 'Claimed')], default='PENDING', max_length=20),
        ),
    ]
