# Generated by Django 4.2.17 on 2024-12-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindness', '0005_alter_donation_status_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('clothes', 'Clothes'), ('books', 'Books'), ('electronics', 'Electronics'), ('other', 'Other')], default='OTHER', max_length=50),
        ),
    ]
