# Generated by Django 4.2.17 on 2024-12-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindness', '0007_alter_donation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='message',
        ),
        migrations.AddField(
            model_name='request',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='requested_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
