# Generated by Django 4.2.17 on 2024-12-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindness', '0008_remove_request_message_request_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('CLAIMED', 'Claimed'), ('EXPIRED', 'Expired'), ('CLOSED', 'Closed')], default='AVAILABLE', max_length=20),
        ),
    ]
