# Generated by Django 4.2.17 on 2024-12-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindness', '0010_role_remove_user_role_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_info',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
