# Generated by Django 4.2.17 on 2025-01-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindness', '0011_rename_contact_info_user_bio_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('CLOTHES', 'Clothes'), ('SHOES', 'Shoes'), ('BOOKS', 'Books'), ('ELECTRONICS', 'Electronics'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
