const statesAndCities = {
    "Abia": ["Umuahia", "Aba", "Ohafia", "Arochukwu", "Isuikwuato", "Bende", "Osisioma", "Ikwuano", "Ngwa", "Ugwunagbo"],
    "Adamawa": ["Yola", "Mubi", "Jimeta", "Ganye", "Numan", "Michika", "Gombi", "Hong", "Song", "Demsa"],
    "Akwa Ibom": ["Uyo", "Ikot Ekpene", "Eket", "Oron", "Abak", "Itu", "Ikot Abasi", "Etinan", "Essien Udim", "Nsit Ubium"],
    "Anambra": ["Awka", "Onitsha", "Nnewi", "Ekwulobia", "Aguleri", "Ogidi", "Ihiala", "Nkpor", "Ozubulu", "Umunze"],
    "Bauchi": ["Bauchi", "Azare", "Misau", "Darazo", "Jama’are", "Katagum", "Alkaleri", "Itas", "Zaki", "Tafawa Balewa"],
    "Bayelsa": ["Yenagoa", "Brass", "Ogbia", "Sagbama", "Nembe", "Ekeremor", "Southern Ijaw", "Kaiama", "Opokuma", "Peremabiri"],
    "Benue": ["Makurdi", "Otukpo", "Gboko", "Katsina-Ala", "Vandeikya", "Tarka", "Ugbokolo", "Agatu", "Oturkpo", "Apa"],
    "Borno": ["Maiduguri", "Biu", "Dikwa", "Konduga", "Ngala", "Gwoza", "Askira", "Kukawa", "Monguno", "Chibok"],
    "Cross River": ["Calabar", "Ikom", "Obudu", "Ogoja", "Ugep", "Akamkpa", "Bekwarra", "Abi", "Obubra", "Yakurr"],
    "Delta": ["Asaba", "Warri", "Sapele", "Ughelli", "Agbor", "Oghara", "Abraka", "Kwale", "Burutu", "Patani"],
    "Ebonyi": ["Abakaliki", "Afikpo", "Onueke", "Ishielu", "Ezza", "Ikwo", "Ohaukwu", "Izzi", "Ohaozara", "Uburu"],
    "Edo": ["Benin City", "Auchi", "Ekpoma", "Ubiaja", "Igueben", "Irrua", "Okada", "Uromi", "Agbor", "Ewatto"],
    "Ekiti": ["Ado-Ekiti", "Ikere", "Ilawe", "Iyin", "Oye", "Aramoko", "Effon", "Ijero", "Ikole", "Igbara-Odo"],
    "Enugu": ["Enugu", "Nsukka", "Oji River", "Agbani", "Udi", "Ezeagu", "Awgu", "Aninri", "Ngwo", "Amagunze"],
    "Gombe": ["Gombe", "Billiri", "Kaltungo", "Dukku", "Deba", "Nafada", "Funakaye", "Shongom", "Bajoga", "Kwami"],
    "Imo": ["Owerri", "Orlu", "Okigwe", "Oguta", "Mbaise", "Mbano", "Isiala Mbano", "Nkwerre", "Oru", "Ehime Mbano"],
    "Jigawa": ["Dutse", "Hadejia", "Gumel", "Birnin Kudu", "Kazaure", "Ringim", "Jahun", "Maigatari", "Yankwashi", "Gagarawa"],
    "Kaduna": ["Kaduna", "Zaria", "Kafanchan", "Saminaka", "Kagoro", "Birnin Gwari", "Ikara", "Kachia", "Giwa", "Jaji"],
    "Kano": ["Kano", "Wudil", "Bichi", "Rano", "Gwarzo", "Dambatta", "Gezawa", "Ungogo", "Kura", "Sumaila"],
    "Katsina": ["Katsina", "Daura", "Funtua", "Malumfashi", "Dutsin-Ma", "Bakori", "Kankia", "Jibia", "Batagarawa", "Charanchi"],
    "Kebbi": ["Birnin Kebbi", "Argungu", "Yelwa", "Zuru", "Bagudo", "Jega", "Koko", "Shanga", "Fakai", "Maiyama"],
    "Kogi": ["Lokoja", "Idah", "Okene", "Kabba", "Ajaokuta", "Dekina", "Ankpa", "Bassa", "Ogori", "Adavi"],
    "Kwara": ["Ilorin", "Offa", "Patigi", "Kaiama", "Jebba", "Omu-Aran", "Ajase-Ipo", "Lafiagi", "Isanlu", "Irepodun"],
    "Lagos": ["Ikeja", "Lagos Island", "Epe", "Badagry", "Ikorodu", "Surulere", "Mushin","Victoria Island", "Lekki", "Ajah", "Apapa", "Yaba", "Festac Town", "Maryland", "Alimosho", "Ojo", "Agege", "Iyana Ipaja", "Shomolu", "Amuwo-Odofin"],
    "Nasarawa": ["Lafia", "Keffi", "Akwanga", "Karu", "Doma", "Nasarawa", "Eggon", "Toto", "Wamba", "Obi"],
    "Niger": ["Minna", "Bida", "Kontagora", "Suleja", "Lapai", "Zungeru", "Kagara", "Mokwa", "Agaie", "Rijau"],
    "Ogun": ["Abeokuta", "Ijebu Ode", "Sango-Ota", "Sagamu", "Ilaro", "Ayetoro", "Ewekoro", "Odeda", "Owode", "Obafemi", "Iperu", "Remo", "Ifo", "Itori", "Ado-Odo", "Idiroko", "Ijebu Igbo", "Ijebu Imushin", "Agbara", "Isara"],
    "Ondo": ["Akure", "Ondo City", "Owo", "Ikare", "Idanre", "Ile-Oluji", "Okitipupa", "Igbokoda", "Bolorunduro", "Ifon"],
    "Osun": ["Osogbo", "Ife", "Ilesa", "Ede", "Ikirun", "Ejigbo", "Iwo", "Okuku", "Ipetumodu", "Modakeke"],
    "Oyo": ["Ibadan", "Ogbomosho", "Iseyin", "Oyo Town", "Saki", "Eruwa", "Kishi", "Igboho", "Fiditi", "Ajawa"],
    "Plateau": ["Jos", "Pankshin", "Shendam", "Barkin Ladi", "Langtang", "Bokkos", "Mangu", "Riyom", "Kanke", "Qua'an Pan"],
    "Rivers": ["Port Harcourt", "Bonny", "Omoku", "Ahoada", "Bori", "Degema", "Okrika", "Abua", "Opobo", "Elele"],
    "Sokoto": ["Sokoto", "Wurno", "Tambuwal", "Binji", "Gwadabawa", "Bodinga", "Goronyo", "Illela", "Isa", "Shagari"],
    "Taraba": ["Jalingo", "Wukari", "Bali", "Gembu", "Zing", "Takum", "Ardo-Kola", "Donga", "Sardauna", "Ibi"],
    "Yobe": ["Damaturu", "Potiskum", "Gashua", "Nguru", "Geidam", "Bade", "Gujba", "Fika", "Bursari", "Machina"],
    "Zamfara": ["Gusau", "Kaura Namoda", "Talata Mafara", "Maradun", "Shinkafi", "Zurmi", "Tsafe", "Bakura", "Anka", "Gummi"],
    "FCT": ["Abuja", "Gwagwalada", "Kuje", "Bwari", "Kwali", "Abaji", "Asokoro", "Maitama", "Wuse", "Garki"],
  };
  
  export default statesAndCities;